# Pytorch basic

## Library

In [1]:
import torch
import numpy as np

## Empty tensor

In [3]:
x = torch.empty(2, 3)
print(x)

tensor([[2.3715e+12, 6.1186e-04, 4.8419e+30],
        [7.0061e+22, 1.9010e-19, 1.8499e+20]])


## Random tensor

In [4]:
x = torch.randn(2, 3)
print(x)

tensor([[ 0.1752,  1.3646, -0.4931],
        [-0.1431,  0.5390,  2.1050]])


## Zero tensor

In [5]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


# Make tensor from list

In [8]:
x = torch.tensor([2.6, 3.4])
print(x)

tensor([2.6000, 3.4000])


# Check tensor size

In [9]:
print(x.size())
print(x.shape)

torch.Size([2])
torch.Size([2])


# Add

In [10]:
x = torch.randn(2, 2, 2)
y = torch.randn(2, 2, 2)
print("x \n", x)
print("y \n", y)
print("x + y\n", x + y)
print("torch.add(x, y) \n", torch.add(x, y))

x 
 tensor([[[-0.4274, -0.7143],
         [ 0.8406, -1.3398]],

        [[ 0.1190,  0.0828],
         [-1.3746,  0.0647]]])
y 
 tensor([[[ 0.4455,  0.0103],
         [-0.6259,  0.6122]],

        [[-0.2064,  0.1025],
         [-0.0019, -0.5788]]])
x + y
 tensor([[[ 0.0180, -0.7040],
         [ 0.2147, -0.7276]],

        [[-0.0874,  0.1853],
         [-1.3765, -0.5141]]])
torch.add(x, y) 
 tensor([[[ 0.0180, -0.7040],
         [ 0.2147, -0.7276]],

        [[-0.0874,  0.1853],
         [-1.3765, -0.5141]]])


## Element-wise multiplication

In [11]:
x = torch.randint(1, 10, (2, 2))
y = torch.randint(1, 10, (2, 2))
print("x \n", x)
print("y \n", y)
print("x * y \n", x * y)

x 
 tensor([[8, 4],
        [9, 7]])
y 
 tensor([[4, 7],
        [1, 3]])
x * y 
 tensor([[32, 28],
        [ 9, 21]])


## Matrix multiplication

In [12]:
x = torch.randint(1, 10, (2, 2))
y = torch.randint(1, 10, (2, 2))
print("x \n", x)
print("y \n", y)
print("x @ y \n", x @ y)
print("torch.matmul(x, y) \n", torch.matmul(x, y))

x 
 tensor([[4, 3],
        [5, 5]])
y 
 tensor([[3, 2],
        [6, 6]])
x @ y 
 tensor([[30, 26],
        [45, 40]])
torch.matmul(x, y) 
 tensor([[30, 26],
        [45, 40]])


## Resize(Reshape in numpy)

In [13]:
x = torch.randint(1, 10, (4, 4))
y = x.view(16)
z = x.view(-1, 8)
print("x \n", x)
print("y \n", y)
print("z \n", z)

x 
 tensor([[7, 2, 7, 9],
        [3, 4, 9, 2],
        [1, 6, 5, 3],
        [1, 8, 9, 3]])
y 
 tensor([7, 2, 7, 9, 3, 4, 9, 2, 1, 6, 5, 3, 1, 8, 9, 3])
z 
 tensor([[7, 2, 7, 9, 3, 4, 9, 2],
        [1, 6, 5, 3, 1, 8, 9, 3]])


## Get a content in tensor

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7008])
-0.7008016109466553


## Convert tensor to numpy

In [16]:
x = torch.ones(3)
a = x.numpy()
print(x)
print(a)

tensor([1., 1., 1.])
[1. 1. 1.]


## Convert numpy to tensor

In [17]:
a = np.ones(3)
x = torch.tensor(a)
y = torch.from_numpy(a)
print("x \n", x)
print("y \n", y)

np.add(a, 1, out=a)
print("x' \n", x)
print("y' \n", y)

x 
 tensor([1., 1., 1.], dtype=torch.float64)
y 
 tensor([1., 1., 1.], dtype=torch.float64)
x' 
 tensor([1., 1., 1.], dtype=torch.float64)
y' 
 tensor([2., 2., 2.], dtype=torch.float64)


## Cuda tensor

In [18]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    # Directly make cuda tensor
    x = torch.ones(2, 3, device=device)
    # CPU tensor
    a = torch.ones(2, 3)
    # Convert cpu tensor to cuda tensor
    y = a.to(device)
    z = (x + y).to(torch.double)
    print("a \n", a)
    print("x \n", x)
    print("y \n", y)
    print("z \n", z)

a 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
x 
 tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
y 
 tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
z 
 tensor([[2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float64)


## Autograd

In [19]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [21]:
print(y.grad_fn)

In [22]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


## Gradients

In [23]:
out.backward()

In [24]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
